- name: Install the python venv
  hosts: localhost
  user: root
  tasks: 
  - name: "Ansible check /opt/python_venvs/ exists"
    stat:
      path: /opt/python_venvs/
    register: p
  - name: "create python virtual environment from the venv folder /opt/python_venvs/ doesn't exist  "
    shell: |
      sudo python3 -m venv /opt/python_venvs/{{ item | basename }}/
      source "/opt/python_venvs/{{ item | basename }}/bin/activate"
      pip install -r "../venv/{{ item | basename }}"
      deactivate
    args:
      executable: /bin/bash
      chdir: "../venv/"
    with_fileglob: "../venv/*.txt"
    loop_control:
      label: "{{ item | basename }}"
    when: p.stat.exists == False
