- name: Install the python venv
  hosts: controlmachine
  user: root
  tasks:                                                                                                       
  - name: create a python virtual environment
    shell: python3 -m venv venv/
  - name: Activate the virtual environment
    shell: source venv/bin/activate
  - name: Install all dependencies
    shell: pip install -r requirements1.txt
