- name: Install the python venv
  hosts: controlmachine
  user: root
  tasks:                                                                                                       
  - name: create a python virtual environment
    shell: python3 -m venv home/ubuntu/venv/
  - name: Activate the virtual environment
    shell: source home/ubuntu/venv/bin/activate
    args:
      executable: /bin/bash
  - name: Install all dependencies
    shell: pip install -r ../venv/requirements1.txt
