- name: Install the python venv
  hosts: localhost
  user: root
  vars:
    requierement: requirements1
  tasks:                                                                                                       
  - name: create a python virtual environment
    shell: python3 -m venv /opt/python_venvs/{{requierement}}/
  - name: Activate the virtual environment
    shell: |
    source /opt/python_venvs/{{requierement}}/bin/activate
    pip install -r "../venv/{{requierement}}.txt"
    deactivate
    

