- name: Install the python venv
  hosts: localhost
  user: root
  vars:
    my_changed_files: "{{ changed_files }}"
  tasks: 
  - debug:
      msg: "{{ item }}"
    with_items: "{{ my_changed_files }}"
   
