- name: Install the python venv
  hosts: localhost
  user: root
  tasks: 
- name: "create python virtual environment from the venv folder"
  shell:
      python3 -m venv "/opt/python_venvs/{{ item | basename }}/"
  args:
    executable: /bin/bash
    chdir: "../venv/"
  with_fileglob: "../venv/*.txt"
  loop_control:
    label: "{{ item | basename }}"
