- name: Install the python venv
  hosts: localhost
  user: root
  vars:
    my_changed_files: "{{ changed_files }}"
  tasks: 
  - name: "create python virtual environment from the  changed files under venv  "
    shell: |
      source "/opt/python_venvs/{{ item | basename }}/bin/activate"
      Installed_package= `pip freez`
      for line in $(cat ../venv/{{ item | basename }}.txt) ;  
         if ! grep $line $Installed_package ;then
            pip install $line
         fi;
      done      
      deactivate
    args:
      executable: /bin/bash
    loop: "{{ changed_files }}"
   
